export const vehicles = [
  {
    id: 'velox-apex',
    slug: 'apex',
    name: 'VELOX Apex',
    category: 'HYPERCAR',
    tagline: 'The Absolute.',
    description: 'A 1,500-horsepower symphony of carbon, titanium, and ambition. The Apex is not measured against competitors — it exists beyond that conversation.',
    price: 'From €2,850,000',
    production: '12 per year',
    specs: {
      power: '1,500 hp',
      torque: '1,250 Nm',
      acceleration: '2.1s (0–100 km/h)',
      topSpeed: '487 km/h',
      weight: '1,190 kg',
      drivetrain: 'AWD Hybrid',
      engine: '6.5L Twin-Turbo V12 + Electric Motor',
      transmission: '9-speed dual-clutch',
    },
    colorways: ['Midnight Obsidian', 'Void Silver', 'Champagne Gold', 'Volcanic Ember'],
    available: true,
    image: 'https://picsum.photos/seed/apex/1600/900',
    heroImage: 'https://picsum.photos/seed/apex-hero/2400/1200',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'velox-spectra',
    slug: 'spectra',
    name: 'VELOX Spectra',
    category: 'GRAND TOURER',
    tagline: 'The Journey Redefined.',
    description: 'Nine hundred horsepower wrapped in hand-stitched leather and silence. The Spectra proves that grand touring and extreme performance are not contradictions.',
    price: 'From €1,450,000',
    production: '22 per year',
    specs: {
      power: '900 hp',
      torque: '950 Nm',
      acceleration: '2.6s (0–100 km/h)',
      topSpeed: '412 km/h',
      weight: '1,420 kg',
      drivetrain: 'RWD',
      engine: '5.5L Twin-Turbo V10',
      transmission: '8-speed dual-clutch',
    },
    colorways: ['Arctic Graphite', 'British Racing Green', 'Solar Bronze', 'Alpine White'],
    available: true,
    image: 'https://picsum.photos/seed/spectra/1600/900',
    heroImage: 'https://picsum.photos/seed/spectra-hero/2400/1200',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'velox-nox',
    slug: 'nox',
    name: 'VELOX Nox',
    category: 'TRACK WEAPON',
    tagline: 'Born Without Compromise.',
    description: 'Road-legal. Track-obsessed. The Nox exists for one purpose: the fastest possible lap time in a machine that carries your name in the chassis.',
    price: 'From €3,200,000',
    production: '8 per year',
    specs: {
      power: '1,200 hp',
      torque: '1,100 Nm',
      acceleration: '2.3s (0–100 km/h)',
      topSpeed: '450 km/h',
      weight: '1,080 kg',
      drivetrain: 'RWD',
      engine: '6.0L Naturally Aspirated V12',
      transmission: '7-speed sequential',
    },
    colorways: ['Race Carbon (exposed)', 'Nox Black', 'Titanium Grey'],
    available: true,
    image: 'https://picsum.photos/seed/nox/1600/900',
    heroImage: 'https://picsum.photos/seed/nox-hero/2400/1200',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'velox-genesis',
    slug: 'genesis',
    name: 'VELOX Genesis',
    category: 'ELECTRIC CONCEPT',
    tagline: 'The Future Arrives.',
    description: 'The Genesis is VELOX\'s declaration that the electric era will not mean the end of passion. Reveal: Q4 2025.',
    price: 'Invite Only',
    production: 'TBC',
    specs: {
      power: '2,000+ hp (est.)',
      torque: 'TBC',
      acceleration: 'Sub 1.8s (est.)',
      topSpeed: '500+ km/h (est.)',
      weight: 'TBC',
      drivetrain: 'AWD Quad-Motor',
      engine: 'Pure Electric',
      transmission: 'Single-speed per axle',
    },
    colorways: ['TBC'],
    available: false,
    image: 'https://picsum.photos/seed/genesis/1600/900',
    heroImage: 'https://picsum.photos/seed/genesis-hero/2400/1200',
    video: 'https://www.w3schools.com/html/mov_bbb.mp4',
  }
];
